name: Create and Merge Release PRs

on:
  workflow_call:
    inputs:
      new_tag:
        description: "The new SemVer tag"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release_pr:
    runs-on: ubuntu-latest
    env:
      NEW_TAG: ${{ inputs.new_tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create, label, and squash-merge Changelog PR into release
        run: |
          PR_URL=$(gh pr create \
            --head changelog/${NEW_TAG} \
            --base release \
            --title "🔖 Update CHANGELOG for ${NEW_TAG}" \
            --body "Automated changelog update for ${NEW_TAG}")
          
          gh pr edit "$PR_URL" --add-label changelog
          
          gh pr merge "$PR_URL" \
            --auto --delete-branch --squash

      - name: Create & auto-merge Release→Production PR
        run: |
          PR_URL=$(gh pr create \
            --head release \
            --base production \
            --title "🔀 Merge ${NEW_TAG} into production" \
            --body "Automated release after tagging ${NEW_TAG}")
          gh pr merge "$PR_URL" \
            --auto --squash
