name: Tag And Publish New Release

on:
  pull_request:
    types: [closed]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  # Create Tag
  semver_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create SemVer Tag and Release
        uses: K-Phoen/semver-release-action@v1.3.2
        with:
          release_branch: release
          release_strategy: release
          tag_format: v%major%.%minor%.%patch%
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish New Release
  create_pr:
    needs: semver_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # full history
          fetch-tags: true

      - name: Debug - Show branch heads and diff
        run: |
          echo "✅ Current branch: $(git rev-parse --abbrev-ref HEAD)"
          git fetch origin production || true
          echo "🔍 Origin/production HEAD:"
          git log origin/production -n 1 --oneline
          echo "🔍 Release HEAD:"
          git log origin/release -n 1 --oneline
          echo "🔀 Diff between release and production:"
          git diff origin/production origin/release --stat || true

      - name: Create Pull Request from release to production
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-to-production     # head branch (source)
          base: production                  # base branch (destination)
          title: 'Merge release into production'
          body: |
            Automated PR: merging release into production after tagging
          commit-message: 'Merge release into production'
          delete-branch: false
