name: Create SemVer Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "The created SemVer tag"
        value: ${{ jobs.semver_changelog.outputs.tag }}

permissions:
  contents: write
  pull-requests: write

jobs:
  semver_changelog:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create SemVer Tag and Release
        id: semver
        uses: K-Phoen/semver-release-action@v1.3.2
        with:
          release_branch: release
          release_strategy: release
          tag_format: v%major%.%minor%.%patch%
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
